version: '3'
services:
  zookeeper:
    image: zookeeper:3.4.11
    ports:
      - "2181:2181"
  kafka_1:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
  kafka_2:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_ADVERTISED_PORT: "9093"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
    depends_on:
      - zookeeper
  kafka_3:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_ADVERTISED_PORT: "9094"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
    depends_on:
      - zookeeper
  kafka_4:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9095:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_ADVERTISED_PORT: "9095"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 4
    depends_on:
      - zookeeper
  kafka_5:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9096:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_ADVERTISED_PORT: "9096"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 5
    depends_on:
      - zookeeper
  kafka_6:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9097:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_ADVERTISED_PORT: "9097"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 6
      KAFKA_CREATE_TOPICS: "foo:48:6:delete,bar:48:6:delete"
    depends_on:
      - zookeeper
      - kafka_1
      - kafka_2
      - kafka_3
      - kafka_4
      - kafka_5