version: '3'
services:
  zookeeper:
    image: zookeeper:3.4.11
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "foo:48:1:delete,bar:48:1:delete"
    depends_on:
      - zookeeper
  producer-consumer-application_1:
    image: producer-consumer-application:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      BOOTSTRAP_SERVERS: ${DOCKER_HOST_IP}:9092
      SERVER_PORT: 8080
    depends_on:
      - prometheus
      - grafana
  producer-consumer-application_2:
    image: producer-consumer-application:1.0.0-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      BOOTSTRAP_SERVERS: ${DOCKER_HOST_IP}:9092
      SERVER_PORT: 8081
    depends_on:
      - prometheus
      - grafana
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring