spring:
  jackson:
    default-property-inclusion: non_absent
    serialization.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    deserialization.READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  kafka:
    consumer:
      group-id: foobar
      auto-offset-reset: latest
    bootstrap-servers: ${BOOTSTRAP_SERVERS}

server.port: 8080

management.endpoints.web.exposure.include: prometheus